vidlyApp/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace vidlyApp.Models
{
    public class Customer
    {
        [Key]
        public int Id { get; set; }


        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        [Display(Name = "Date of Birth")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? BithDate { get; set; }
        public bool IsSubscribeToNewsletter { get; set; }

        [Display(Name = "MemberShip Type")]
        public MemberShiptype MemberShiptype { get; set; }

        public int MemberShiptypeId { get; set; }


    }
}

vidlyApp/Models/DemoContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace vidlyApp.Models
{
    public class DemoContext:DbContext
    {
        public DemoContext():base("vid")
        {
            this.Configuration.LazyLoadingEnabled = false;

        }
     
        public DbSet<Customer> cutomers { get; set; }

        public DbSet<Movie> Movies { get; set; }
        public DbSet<Genre> Genres { get; set;
        }
        public DbSet<MemberShiptype> MemberShipTypes { get; set; }
      
    }
}

vidlyApp/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace vidlyApp.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

vidlyApp/Models/MemberShiptype.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace vidlyApp.Models
{
    public class MemberShiptype
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public short SignUpFee { get; set; }
        public byte DurationInMont { get; set; }

        public byte DiscountInRate { get; set; }
    }

}

vidlyApp/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace vidlyApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        [Required]
        [Column(TypeName = "nvarchar")]
        [MaxLength(50)]
        public string Name { get; set; }

        [DisplayFormat(DataFormatString = "{0:MMM-dd,yyyy}",ApplyFormatInEditMode =true)]
        public DateTime ReleaseDate { get; set; }

        [DisplayFormat(DataFormatString ="{0:MMM-dd,yyyy}",ApplyFormatInEditMode =true)]
        public DateTime DateAdded { get; set; }

        public int Stock { get; set; }

        public Genre Genre { get; set; }
        public int GenreId { get; set; }
    }
}

vidlyApp/Controllers/CstoemrController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vidlyApp.DataViewModel;
using vidlyApp.Models;
using System.Data.Entity;

namespace vidlyApp.Controllers
{
    public class CstoemrController : Controller
    {
        private DemoContext _context = new DemoContext();
        public CstoemrController()
        {
            _context = new DemoContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Cstoemr


            public ActionResult Index()
        {
            var cus = _context.cutomers.Include(x => x.MemberShiptype).ToList();
            return View(cus);
        }

        [HttpGet]
        public ActionResult New()
        {
            var MenberShiplist = _context.MemberShipTypes.ToList();
            // ViewBag.MemBerList = MenberShiplist;
            var NewcustomerViewList = new NewCustomerViewModel
            {
                MemberShiptypes = MenberShiplist
            };
            return View("CustomerForm", NewcustomerViewList);
           // return View();

        }

        [HttpPost]
        public ActionResult AddCurtomers(Customer obj)
        {
        
            if(obj.Id==0)
            {

                _context.cutomers.Add(obj);
               
            }
            else
            {
                var customer = _context.cutomers.Single(x => x.Id == obj.Id);
                customer.Name = obj.Name;
                customer.BithDate = obj.BithDate;
                customer.MemberShiptype = new MemberShiptype { Id = Convert.ToInt32(obj) };
                customer.IsSubscribeToNewsletter = obj.IsSubscribeToNewsletter;
                _context.cutomers.Add(customer);
            }
            _context.SaveChanges();

            return RedirectToAction("New");
        }

        public ActionResult Edit(int id)
        {
            Customer objCus = _context.cutomers.SingleOrDefault(a => a.Id == id);
            if (objCus == null)
            {
                return HttpNotFound();
            }

            var ViewModel = new NewCustomerViewModel
            {
                Customer = objCus,
                MemberShiptypes = _context.MemberShipTypes.ToList()
        };
            return View("CustomerForm", ViewModel);
        }
    }
}

vidlyApp/Views/Cstoemr/CustomerForm.cshtml
@*@model vidlyApp.Models.Customer*@

@model vidlyApp.DataViewModel.NewCustomerViewModel
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New</h2>
<h2>AddCurtomers</h2>
@using (Html.BeginForm("AddCurtomers", "Cstoemr", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="control-label">Name</label>
        @Html.TextBoxFor(x => x.Customer.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Customer.BithDate)
        @Html.TextBoxFor(x => x.Customer.BithDate,"{0:d MMM yyyy}", new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Customer.MemberShiptype)
        @Html.DropDownListFor(x => x.Customer.MemberShiptype, new SelectList(Model.MemberShiptypes, "Id", "Name"), "-Select MemberShip", new { @class = "form-control" })
    </div>
    @*<div class="form-group">
        @Html.LabelFor(x=>x.MemberShiptype)
        @Html.DropDownListFor(x=>x.MemberShiptypeId,new SelectList(ViewBag.MemBerList, "Id","Name"),"-Select MemberShip-",new { @class="form-control"})
    </div>*@
    <div class="checkbox">
        <label>@Html.CheckBoxFor(x => x.Customer.IsSubscribeToNewsletter) Subscribe for News letter ?</label>
    </div>
    @Html.HiddenFor(x=>x.Customer.Id)
    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-send"></span>Save</button>

}

vidlyApp/Views/Cstoemr/Index.cshtml
@model IEnumerable<vidlyApp.Models.Customer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "New")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MemberShiptype.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BithDate)
        </th>
        <th>
           Member Ship
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsSubscribeToNewsletter)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BithDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MemberShiptype.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsSubscribeToNewsletter)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

vidlyApp/Views/Customer/AddCurtomers.cshtml
@model vidlyApp.DataViewModel.NewCustomerViewModel
@{
    ViewBag.Title = "AddCurtomers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddCurtomers</h2>
@using (Html.BeginForm("AddCurtomers", "Customer", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="control-label">Name</label>
        @Html.TextBoxFor(x => x.Customer.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Customer.BithDate)
        @Html.TextBoxFor(x => x.Customer.BithDate, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Customer.MemberShiptype)
        @Html.DropDownListFor(x => x.Customer.MemberShiptype, new SelectList(Model.MemberShiptypes, "Id", "Name"), "-Select MemberShip", new { @class="form-control" })
    </div>
    <div class="checkbox">
        <label>@Html.CheckBoxFor(x => x.Customer.IsSubscribeToNewsletter) Subscribe for News letter ?</label>
    </div>
    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-send"></span>Save</button>

}

vidlyApp/Views/Customer/Details.cshtml
@model vidlyApp.Models.Customer
  

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
          
       
        </dd>
        @if (Model.BithDate!=null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.BithDate)
                
            </dt>
            <dd>
                @Html.DisplayFor(a => a.BithDate, "dd/MMMM/yyyy=>") @*@Html.EditorFor(a => a.BithDate, "dd/MM/yyyy")*@
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.IsSubscribeToNewsletter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSubscribeToNewsletter)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MemberShiptype.DiscountInRate)

        </dt>
        <dd>
            @Html.DisplayFor(model => model.MemberShiptype.DiscountInRate) %
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

vidlyApp/Views/Customer/Index.cshtml
@model IEnumerable<vidlyApp.Models.Customer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!Model.Any())
{
    <p class="alert alert-danger">We Don't have any Customer yet..!</p>
}
else
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-bordered table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsSubscribeToNewsletter)

            </th>

            <th>Discount Name</th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
              
                <td>
                    @Html.EditorFor(modelItem => item.IsSubscribeToNewsletter)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberShiptype.Name)%
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink(item.Name, "Details", "Customer", new { id = item.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}

vidlyApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

vidlyApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

vidlyApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

vidlyApp/Views/Movie/Details.cshtml
@model vidlyApp.Models.Movie
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<table class="table tab-content table-bordered">
    <thead>
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Genre.Name)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th class="text-center">
                Genre
            </th>
          
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.Genre.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.DateAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Stock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Genre.Name)
            </td>
        </tr>
    </tbody>

</table>

vidlyApp/Views/Movie/Index.cshtml
@model IEnumerable<vidlyApp.Models.Movie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table tab-content table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateAdded)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stock)
        </th>
        <th>
            Genre
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Genre.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateAdded)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stock)
        </td>
        <td>
            @Html.DisplayFor(modelItem=>item.Genre.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

vidlyApp/Views/Movie/Index1.cshtml
@model vidlyApp.Models.Customer

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm("Index1","Movie",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

vidlyApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>